### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by kaishin** [kylehickinson/SwiftUI-WebView#1]
Would you consider adding an [open-source license](https://opensource.org/licenses) to this project? Without one, many will hesitate to  use it in production codebases.

Quoting [opensource.org](https://opensource.org/faq#approved-licenses-only):

> Can I call my program "Open Source" even if I don't use an approved license?
Please don't do that. If you call it "Open Source" without using an approved license, you will confuse people.

**Comment by kylehickinson** [comment]
Added in f6b2117
