### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by darindimitroff** [kylehickinson/SwiftUI-WebView#2]
Can't seem to get the package working under SwiftUI macOS projects. Looking at the code I saw support for all platforms, maybe there is something iOS specific in there? Thanks for the awesome package.

**Comment by kaishin** [comment]
This project doesn't support macOS. I've already done it here in interested:

https://github.com/kaishin/Markoff/blob/markoff-2/Markoff/Sources/Views/WebView.swift

I'd open a PR but waiting for #1 to be addressed first.

**Comment by darindimitroff** [comment]
Thanks, I manually re-implemented your iOS solution for macOS. Wasn't too hard, took me about a day with minimal knowledge. Awesome project 🙌
